name: "Create draft release"

on:
  push:
    branches:
      - checkpoint_1
      - checkpoint_2
      - checkpoint_3
      - main

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}